spring:
  application:
    name: finance-control-api

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    secret: ${SECURITY_SECRET}
    expiration: ${SECURITY_EXPIRATION}

server:
  port: 8080
  servlet:
    context-path: /nix-finance-api

app:
  saas:
    plans:
      free:
        category-limit: ${APP_CATEGORY-LIMIT}
  rate-limit:
    enabled: ${APP_RATE_LIMIT_ENABLED:true}
    global:
      requests-per-minute: ${APP_RATE_LIMIT_GLOBAL_REQUESTS_PER_MINUTE:100}
    auth:
      requests-per-minute: ${APP_RATE_LIMIT_AUTH_REQUESTS_PER_MINUTE:5}

spring.threads.virtual.enabled: true
